export const FETCH_CAR = "FETCH_CAR";
export const SAVE_CAR = "SAVE_CAR";
export const PURGE_CAR_EDITOR = "PURGE_CAR_EDITOR";
export const CREATE_NEW_COMPLECTATION = "CREATE_NEW_COMPLECTATION";
export const SET_COMPLECTATION_OPTIONS = "SET_COMPLECTATION_OPTIONS";
export const CHANGE_COMPLECTATION_NAME = "CHANGE_COMPLECTATION_NAME";
