export const FETCH_CAR = "FETCH_CAR";
export const SAVE_CAR = "SAVE_CAR";
export const PURGE_CAR_EDITOR = "PURGE_CAR_EDITOR";
export const CREATE_NEW_COMPLECTATION = "CREATE_NEW_COMPLECTATION";
export const SET_COMPLECTATION_OPTIONS = "SET_COMPLECTATION_OPTIONS";
export const SAVE_CAR_IMAGES = "SAVE_CAR_IMAGES";
export const SAVE_CAR_COLORS = "SAVE_CAR_COLORS";
export const DELETE_COMPLECTATION = "DELETE_COMPLECTATION";
