export const OPEN_CREATE_TRANSMISSION_MODAL = "OPEN_CREATE_TRANSMISSION_MODAL";
export const OPEN_EDIT_TRANSMISSION_MODAL = "OPEN_EDIT_TRANSMISSION_MODAL";
export const CREATE_NEW_TRANSMISSION = "CREATE_NEW_TRANSMISSION";
export const EDIT_TRANSMISSION = "EDIT_TRANSMISSION";
export const DELETE_TRANSMISSION = "DELETE_TRANSMISSION";
