export const UPDATE_TRANSMISSION_MODAL_OPEN = "UPDATE_TRANSMISSION_MODAL_OPEN";
export const UPDATE_TRANSMISSION = "UPDATE_TRANSMISSION";
export const UPDATE_TRANSMISSION_FIELD = "UPDATE_TRANSMISSION_FIELD";
