export const OPEN_CREATE_ENGINE_MODAL = "OPEN_CREATE_ENGINE_MODAL";
export const OPEN_EDIT_ENGINE_MODAL = "OPEN_EDIT_ENGINE_MODAL";
export const CREATE_NEW_ENGINE = "CREATE_NEW_ENGINE";
export const EDIT_ENGINE = "EDIT_ENGINE";
export const DELETE_ENGINE = "DELETE_ENGINE";
