export const OPEN_COMPLECTATION_EDIT_MODAL = "OPEN_COMPLECTATION_EDIT_MODAL";
export const COPY_COMPLECTATION_DATA = "COPY_COMPLECTATION_DATA";
export const CLEAN_UP_COMPLECTATION = "CLEAN_UP_COMPLECTATION";
export const SET_COMPLECTAION_OPTIONS = "SET_COMPLECTAION_OPTIONS";
export const SET_POWER_UNIT_OPTION = "SET_POWER_UNIT_OPTION";
export const DELETE_POWER_UNIT = "DELETE_POWER_UNIT";
export const CREATE_NEW_POWER_UNIT = "CREATE_NEW_POWER_UNIT";
export const SAVE_COMPLECTATION = "SAVE_COMPLECTATION";
