export const OPEN_COMPLECTATION_EDIT_MODAL = "OPEN_COMPLECTATION_EDIT_MODAL";
export const COPY_COMPLECTATION_DATA = "COPY_COMPLECTATION_DATA";
export const CLEAN_UP_COMPLECTATION = "CLEAN_UP_COMPLECTATION";
export const SET_COMPLECTAION_OPTIONS = "SET_COMPLECTAION_OPTIONS";
